apiVersion: v1
kind: Service
metadata:
  namespace: kic
  name: kic-frontend-service
spec:
  ports:
    - port: 19006
      name: http
  selector:
    app: kic-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kic
  name: kic-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kic-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: kic
      labels:
        app: kic-frontend
    spec:
      containers:
        - image: gcr.io/keeping-it-casual/kic-frontend:dev
          name: kic-frontend
          ports:
            - containerPort: 19006
